/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package movies.stream;

import movies.stream.view.MovieView;

public class Main {
    public static void main(String args[]) {
    	new MovieView().getOption();
    }
}
